### ISSUE TITLE
PasswordAunthentication no longer set to false

### ISSUE THREAD

**Issue by Tejeev** [superseb/tf-do-rancher2#41]
PasswordAuthentication on ubuntu images is not set to false. I thought this was set to true in earlier versions.

**Comment by superseb** [comment]
@Tejeev Can you share a bit more context on the issue? I've just checked the droplet for rancher and droplet for downstream cluster, and they both show the same:

```
# grep -i passwordauthentication /etc/ssh/sshd_config
PasswordAuthentication no
# PasswordAuthentication.  Depending on your PAM configuration,
# PAM authentication, then enable this but set PasswordAuthentication
```

The only way I've seen this differently is if I don't specify my SSH key and I get an auto-generated password e-mailed to me which I then need to use.
